version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  install-and-lint-node10:
    executor:
      name: node/default
      tag: "10.4"
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
  install-and-lint-node8:
    executor:
      name: node/default
      tag: "8.17"
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
workflows:
    install-and-lint:
      jobs:
        - install-and-lint-node10
        - install-and-lint-node8
