name: Node.js CI

on: [push]

jobs:
  my_first_job:
    name: hello
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm run lint
      env:
        CI: true
        
  my_second_job:
    name: heyyyy
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run build --if-present
    - run: npm run lint
      env:
        CI: true
        
        
  my_third_job:
    name: heyyyy
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run build --if-present
      - run: npm run lint
        env:
          CI: true
